### ISSUE TITLE
Route regex not working for numbers

### ISSUE THREAD

**Issue by jakub-astrahit** [Graidenix/vanilla-router#6]
Hi, I'm trying to set up this route:
http://localhost:3002/#2016-12-16/report

by using this:
```
router.add('(:num)-(:num)-(:num)/report', function(year, month, day) {
console.log(year, month, day);
});
```

but it's not working. It acts as if the URL doesn't exist. Any idea what am I doing wrong please?

**Comment by Graidenix** [comment]
Fixed
