### ISSUE TITLE
Changing hash in url doesn't change view

### ISSUE THREAD

**Issue by jakub-astrahit** [Graidenix/vanilla-router#7]
Hi, when I load a page, then I manually change the URL after the hash (I'm using the hash mode) in the address bar and hit enter, nothing will happen. What do I need to do to make this work?

**Comment by Graidenix** [comment]
Hi @jakub2,
Please use `router.addUriListener()`.
It sets the listeners for hashChange for "hash mode" and stateChange for "history".
Let me know if this fixed your issue.

**Comment by jakub-astrahit** [comment]
It did help. Thank you, but it seems like after your last commit there is this "confirm leaving page" dialog when I try to refresh the page - here is a screenshot: http://3.1m.yt/bRBExy0.png

Why is that?

**Comment by Graidenix** [comment]
Fixed
