### ISSUE TITLE
Internet Explorer 'Promise' is undefined

### ISSUE THREAD

**Issue by jakub-astrahit** [Graidenix/vanilla-router#8]
In Internet Explorer, the router gives me this error: 'Promise' is undefined.
This is what it shows in my console:
`return this._currentPage&&this._currentPage.options&&this._currentPage.options.unloadCb?(e=this._currentPage.options.unloadCb(this._currentPage,t),!t||e instanceof Promise?e:e?Promise.resolve(e):Promise.reject(e)):t?Promise.resolve(!0):!0}`

**Comment by Graidenix** [comment]
Fixed
